PR: 공용컴포넌트 image_box 작업했습니다.
2023-frontend1/Paprika-Market-2.0.1 pull request #5
Opened 2023-11-27 14:13 UTC by snkchan

## 작업 결과물 
- _Image or Video_
- _component 등 출력물 한정_

- <img width="826" alt="pr_image-box" src="https://github.com/2023-frontend1/Paprika-Market-2.0.1/assets/144839872/1039cd64-d697-431e-afba-d4c9950dd763">
- <img width="805" alt="pr_image-box1" src="https://github.com/2023-frontend1/Paprika-Market-2.0.1/assets/144839872/e994d80a-d5eb-4298-bbd7-051eebf5bba0">
<br/>

## 작업 상세 내용

- 공용컴포넌트 imageBox 사이즈별로 작업했습니다. 
- props로는 size(witdth,height), shape(rectangle or round) 두가지 전달 가능
- 위의 사진 1~5번 처럼 페이지별로 5가지 size와 shape에 맞춰 예시로 올려뒀습니다.

<br/> 

<br/>
<br/>

## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] reviewer 설정 확인
- [x] Assignees 설정 확인

<br/>

--------------------
🔴 **(Optional) 이건 반드시 확인해 주세요!**

- shapeCss, sizeCss의 키이름을 임의로 정해봤는데 더 좋은아이디어 있으면 comment부탁드립니다.
- width,height 크기를 px단위로 설정했는데 문제가될지 확인 부탁드립니다.

<br/>

--------------------
🟡 **리뷰 작성시, 다음의 형식을 작성바랍니다.!**

- _코드 수정을 요청할 때만, 아래 형식을 맞춰주세요!!_

```text
# Comment Level
  - [ ] N : "변경을 꼭 소원합니다. 🔥" 
  - [ ] M : "좋지만, 난 좀 그래요..🥹"
  - [ ] S : "그냥 멘트입니다. 👍"

# Description

```

2023-11-27 15:13 UTC, TransparentDeveloper commented
100점.. 100점이요 👍 (물론 개인의견입니다. 😄)

2023-11-27 16:40 UTC, TransparentDeveloper requested changes
하나만.. 수정요청 남깁니다.. 뒤끝 죄송합니다...ㅠㅠㅠ

2023-11-27 16:40 UTC, TransparentDeveloper commented on src/components/image_box.jsx
> +}
# Comment Level
  - [ ] N : "변경을 꼭 소원합니다. 🔥" 
  - [x] M : "좋지만, 난 좀 그래요..🥹"
  - [ ] S : "그냥 멘트입니다. 👍"

# Description
규격을 미리 정하는 것보다 추후에 개발자들이 유동적으로 적절한 width, height 를  입력해서 사용하는 게 어떨까요? ImageBox 를 활용하는 다른 컴포넌트 들 규격도 이 크기에 맞춰서 개발해야돼서 유지보수할 때 힘들 것 같습니다.

2023-11-27 17:07 UTC, snkchan commented on src/components/image_box.jsx
> +}
[chore: size속성을 width,height로 나눠서 전달받도록 변경](https://github.com/2023-frontend1/Paprika-Market-2.0.1/pull/5/commits/34d528d24c46f04ba1850356ba4fca3ed268a4fa)
- 좋은것 같아요 반영해서 size props를 witdth,height 두가지로 나눠서 전달받도록 코드 수정했습니다.
- 사용하실때 원하는 witdth,height 값 직접입력하셔서 사용하시면 됩니다.

2023-11-27 20:06 UTC, TransparentDeveloper approved these changes

2023-11-28 03:11 UTC, hyetjs commented
# Comment Level
  - [ ] N : "변경을 꼭 소원합니다. 🔥" 
  - [ ] M : "좋지만, 난 좀 그래요..🥹"
  - [x] S : "그냥 멘트입니다. 👍"

# Description
채윤님 고생하셨습니다! 완전 잘 만드셨어요! 윤신님 의견 좋은 것 같아요!

2023-11-28 13:14 UTC, merged