PR: Design/layout (Header,Footer,CenterBox) 작업했습니다.
2023-frontend1/Paprika-Market-2.0.1 pull request #9
Opened 2023-11-28 15:47 UTC by snkchan

## 작업 결과물 
- _Image or Video_
- _component 등 출력물 한정_

- A
- <img width="1278" alt="pr_center-box" src="https://github.com/2023-frontend1/Paprika-Market-2.0.1/assets/144839872/ecb1aa0f-afec-47f6-9aff-28fd48a5e03c">
- B
-  <img width="1279" alt="pr_layout" src="https://github.com/2023-frontend1/Paprika-Market-2.0.1/assets/144839872/a698d863-1454-4863-a9e5-cdecdb78610c">

<br/> 
<br/>

## 작업 상세 내용

- 세가지 작업했습니다.
- A : CenterBox컴포넌트  모든페이지에서 적용될 가운데 정렬을 위한 Box생성, 2번박스안쪽으로 모든 내용이 들어가도록 만들었습니다

<br/>
<br/>

## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] reviewer 설정 확인
- [x] Assignees 설정 확인

<br/>

--------------------
🔴 **(Optional) 이건 반드시 확인해 주세요!**

<br/>

--------------------
🟡 **리뷰 작성시, 다음의 형식을 작성바랍니다.!**

- _코드 수정을 요청할 때만, 아래 형식을 맞춰주세요!!_

```text
# Comment Level
  - [ ] N : "변경을 꼭 소원합니다. 🔥" 
  - [ ] M : "좋지만, 난 좀 그래요..🥹"
  - [ ] S : "그냥 멘트입니다. 👍"

# Description

```

2023-11-28 16:14 UTC, TransparentDeveloper requested changes
리뷰 남깁니다.;)

2023-11-28 16:14 UTC, TransparentDeveloper commented on src/components/layouts/componets/center_box.jsx
> +	max-width: 46%;
# Comment Level
  - [ ] N : "변경을 꼭 소원합니다. 🔥" 
  - [ ] M : "좋지만, 난 좀 그래요..🥹"
  - [x] S : "그냥 멘트입니다. 👍"

# Description
46? 의미심장한 숫자로군요? ㅋㅋ 
왜 max-width 로 설정했나요?

2023-11-28 16:14 UTC, TransparentDeveloper commented on src/components/layouts/constants/help-catagory.ts
# Comment Level
  - [x] N : "변경을 꼭 소원합니다. 🔥" 
  - [ ] M : "좋지만, 난 좀 그래요..🥹"
  - [ ] S : "그냥 멘트입니다. 👍"

# Description
- `help-category.ts`, `more-about-catagory.ts`, `service-catagroy.ts` 하나의 파일로 압축하는 게 더 좋을 것 같습니다. 그럼 배럴파일도 없앨 수 있구요. 이건 고려 한번 해주십사 적었습니다..

- 컨벤션에 따르면 파일명은 snake_case 입니당 😄

2023-11-28 16:14 UTC, TransparentDeveloper commented on src/components/layouts/constants/help-catagory.ts
> +const HelpCatagory = [
# Comment Level
  - [x] N : "변경을 꼭 소원합니다. 🔥" 
  - [ ] M : "좋지만, 난 좀 그래요..🥹"
  - [ ] S : "그냥 멘트입니다. 👍"

# Description
- 컨벤션에 따르면 변수명은 camelCase 입니당 😄

2023-11-28 16:21 UTC, snkchan commented on src/components/layouts/constants/help-catagory.ts
> +const HelpCatagory = [
[refactor: constants폴더내용을 constant.ts파일 하나로 합침](https://github.com/2023-frontend1/Paprika-Market-2.0.1/pull/9/commits/3cb0f2817dd8ae08fd965bc1c3c33b5da60eeaca)
- 죽여주십쇼,,, 수정했습니다.

2023-11-28 16:24 UTC, snkchan commented on src/components/layouts/constants/help-catagory.ts
[refactor: constants폴더내용을 constant.ts파일 하나로 합침](https://github.com/2023-frontend1/Paprika-Market-2.0.1/pull/9/commits/3cb0f2817dd8ae08fd965bc1c3c33b5da60eeaca)
- 반영해서 수정했습니다. 잘못수정해서 다시 commit했어요
- [fix: 잘못 import된 constant 수정](https://github.com/2023-frontend1/Paprika-Market-2.0.1/pull/9/commits/5b2aaaea73a8cdeec1cfc1284a27175dfbeb0e00)

2023-11-28 16:27 UTC, snkchan commented on src/components/layouts/componets/center_box.jsx
> +	max-width: 46%;
<img width="914" alt="pr_comment" src="https://github.com/2023-frontend1/Paprika-Market-2.0.1/assets/144839872/71d4afe3-47a1-4b55-b9df-e398374e7264">
- 작업하다보니 기존50%에서는 초록색너비를 차지해서  46%를 적용하면 더 적당한크기로보여서 수정했습니다

2023-11-28 17:09 UTC, TransparentDeveloper requested changes
채윤님..아직 끝나지 않았습니다.

2023-11-28 17:09 UTC, TransparentDeveloper commented on src/components/layouts/constant.ts
# Comment Level
  - [x] N : "변경을 꼭 소원합니다. 🔥" 
  - [ ] M : "좋지만, 난 좀 그래요..🥹"
  - [ ] S : "그냥 멘트입니다. 👍"

# Description
.ts 라...ㅋㅋㅋ 드디어 밝혀졌네요. 남몰래 타입스크립트 공부한거 걸렸죠. ㅎ

2023-11-29 08:52 UTC, hyetjs commented
# Comment Level
  - [ ] N : "변경을 꼭 소원합니다. 🔥" 
  - [ ] M : "좋지만, 난 좀 그래요..🥹"
  - [x] S : "그냥 멘트입니다. 👍"

# Description
고생많으셨습니다! 확인했습니다👍

2023-11-29 13:41 UTC, TransparentDeveloper approved these changes
고생하셨습니다.

2023-11-29 14:55 UTC, TransparentDeveloper approved these changes

2023-11-29 14:56 UTC, hyetjs approved these changes
굳굳 👍

2023-11-29 15:15 UTC, merged